### ISSUE TITLE
underscore in roxygen2 documentation sometimes renders as \emph

### ISSUE THREAD

**Issue by roseodea** [wviechtb/mathjaxr#7]
Hi @wviechtb, I'm having problems with `_` and `\_` in mathjaxr equations being interpreted as `\emph` and `\\emph`.

Reproducible examples: [https://github.com/roseodea/UnderscoreProblem](https://github.com/roseodea/UnderscoreProblem)

Do you have any advice for this problem?

Thanks,
Rose

**Comment by wviechtb** [comment]
First of all, thanks for raising such a well-documented issue. The problem stems not from `mathjaxr` itself but the use of markdown parsing in `roxygen2` (https://roxygen2.r-lib.org/articles/rd-formatting.html). In markdown, underline characters are used to indicate emphasized text. To avoid this happening in equations, `roxygen2` does not interpret underlines as markdown within certain Rd tags including `\eqn` and `\deqn` but it does not know about the macros provided by `mathjaxr` (e.g., `\mjdeqn`). You can switch off markdown parsing (which you have globally enabled with `Roxygen: list(markdown = TRUE)` in `DESCRIPTION`) using the `@noMd` tag (the `@md` you used is superfluous since markdown parsing is already enabled globally), but it does not seem to be possible to just disable it for certain parts of a single help file. Why sometimes underlines are converted to `\emph` and sometimes not is not clear to me, but this has to do with the underlying rules for markdown parsing. Maybe there is a trick one could exploit here to avoid the parsing, but ultimately, I think this needs to be addressed in `roxygen2` itself (not sure what the best solution is, but maybe it should be possible to allow the specification of macro names within which no markdown parsing is done).

**Comment by bwiernik** [comment]
@wviechtb I think the roxygen2 folks would accept a pull request adding the mathjaxr tags to the vector of escaped Rd tags here https://github.com/r-lib/roxygen2/blob/master/R/markdown-escaping.R#L32

**Comment by wviechtb** [comment]
@bwiernik While that may be a possibility, those tags are the 'official' Rd ones (as far as I can tell) and I am not sure if people should be suggesting to add 'their' tags to that list. This could really get out of hand and there might be clashes. Instead, it might be better if there was a way to specify tags to be ignored via `DESCRIPTION`, for example by expanding on `Roxygen: list(markdown = TRUE)` and allowing that list to include additional tags to be specified for which markdown parsing should be ignored.

**Comment by wviechtb** [comment]
Happy to see that `roxygen2` now escapes the `mathjaxr` tags (and thanks to @bwiernik for making the pull request): https://github.com/r-lib/roxygen2/pull/1231

**Comment by bwiernik** [comment]
Awesome! I'd forgotten about this!

**Comment by roseodea** [comment]
Thanks!
